let questions = [
    {id: 1, text: "Pourquoi suis-je collant ?"},
    {id: 2, text: "Qu'est-ce qui réveille mon voisin au beau milieu de la nuit ?"},
    {id: 3, text: "Qu'est-ce qui a ruiné mon dernier rendez-vous ?"},
    {id: 4, text: "Quelle est ma nouvelle obsession ?"},
    {id: 5, text: "Pourquoi je ne peux pas dormir la nuit ?"},
    {id: 6, text: "Qu'est-ce qui est en train de rendre la vie difficile au camping ?"},
    {id: 7, text: "Qu'est-ce qui fait rire le Père Noël ?"},
    {id: 8, text: "Qu'est-ce qui provoque des crises chez les hipsters ?"},
    {id: 9, text: "Que trouvera-t-on dans ma cave ?"},
    {id: 10, text: "Pourquoi ma dernière relation a-t-elle échoué ?"},
    {id: 11, text: "Qu'est-ce qui m'empêche de me concentrer ?"},
    {id: 12, text: "Qu'est-ce que la sorcière a utilisé pour sa potion ?"},
    {id: 13, text: "Quelle est ma nouvelle stratégie de séduction ?"},
    {id: 14, text: "Qu'est-ce qui a surpris le détective lors de son enquête ?"},
    {id: 15, text: "Qu'est-ce qui a provoqué la dernière dispute en famille ?"},
    {id: 16, text: "Qu'est-ce qui pourrait bien ruiner ma prochaine fête ?"},
    {id: 17, text: "Qu'est-ce qui a ruiné mon enfance ?"},
    {id: 18, text: "Qu'est-ce qui a été banni lors du dernier pique-nique familial ?"},
    {id: 19, text: "Qu'est-ce qui a déclenché la dernière apocalypse zombie ?"},
    {id: 20, text: "Qu'est-ce qui motive vraiment le Père Noël ?"},
    {id: 21, text: "Qu'est-ce qui met fin à ma soirée romantique ?"},
    {id: 22, text: "Qu'est-ce qui est responsable de la fonte des glaces ?"},
    {id: 23, text: "Qu'est-ce qui est arrivé par la poste ce matin ?"},
    {id: 24, text: "Qu'est-ce qui fait battre mon cœur plus vite ?"},
    {id: 25, text: "Qu'est-ce qui a fait fuir mon dernier assistant ?"},
    {id: 26, text: "Qu'est-ce qui a fait exploser le micro-ondes ?"},
    {id: 27, text: "Qu'est-ce qui a causé la dernière crise économique ?"},
    {id: 28, text: "Qu'est-ce qui a effrayé le monstre sous mon lit ?"},
    {id: 29, text: "Qu'est-ce qui est étrangement satisfaisant ?"},
    {id: 30, text: "Qu'est-ce qui est interdit au Paradis ?"},
    {id: 31, text: "Qu'est-ce qui a causé mon dernier fou rire ?"},
    {id: 32, text: "Qu'est-ce qui m'a fait vomir au dernier repas familial ?"},
    {id: 33, text: "Qu'est-ce qui amène le chaos à chaque fête de bureau ?"},
    {id: 34, text: "Qu'est-ce qui a finalement vaincu King Kong ?"},
    {id: 35, text: "Qu'est-ce qui rend mon thérapeute mal à l'aise ?"},
    {id: 36, text: "Qu'est-ce qui fait toujours pleurer le bébé ?"},
    {id: 37, text: "Qu'est-ce qui a été découvert dans la chambre secrète ?"},
    {id: 38, text: "Qu'est-ce qui me donne des super-pouvoirs ?"},
    {id: 39, text: "Qu'est-ce qui me fait rougir à chaque fois ?"},
    {id: 40, text: "Qu'est-ce qui est inacceptable en société ?"},
    {id: 41, text: "Qu'est-ce qui s'est avéré être une grosse erreur ?"},
    {id: 42, text: "Qu'est-ce qui est caché dans le placard de grand-mère ?"},
    {id: 43, text: "Qu'est-ce qui a causé ma dernière insomnie ?"},
    {id: 44, text: "Qu'est-ce qui a surpris tout le monde lors de la réunion de famille ?"},
    {id: 45, text: "Qu'est-ce qui a fait mon succès à la dernière audition ?"},
    {id: 46, text: "Qu'est-ce qui a fait dérailler le train du plaisir ?"},
    {id: 47, text: "Qu'est-ce qui s'avère être mon pire cauchemar ?"},
    {id: 48, text: "Qu'est-ce qui fait grincer des dents à chaque réunion ?"},
    {id: 49, text: "Qu'est-ce qui est devenu mon nouveau passe-temps ?"},
    {id: 50, text: "Qu'est-ce qui est sorti de la boîte de Pandore ?"},
];


export default questions;
