let reponses = [
    {id: 1, text: "Un défilé de modèles en chaise roulante."},
    {id: 2, text: "Transformer des orphelins en smoothies."},
    {id: 3, text: "Un montage de mes erreurs."},
    {id: 4, text: "Des arrière-grands-parents super sexy."},
    {id: 5, text: "L'odeur douce et sucrée de la vengeance."},
    {id: 6, text: "Un singe qui fume un cigare."},
    {id: 7, text: "Un bon coup de fourchette."},
    {id: 8, text: "Faire exploser les pigeons pour le fun."},
    {id: 9, text: "La lente et inexorable marche vers la mort."},
    {id: 10, text: "Un bébé qui vous regarde fixement."},
    {id: 11, text: "Faire une collecte de fonds pour les riches."},
    {id: 12, text: "Un dauphin qui parle."},
    {id: 13, text: "Une danse exotique avec des poupées gonflables."},
    {id: 14, text: "Un retour gênant chez le médecin."},
    {id: 15, text: "Une baguette magique qui ne fonctionne pas."},
    {id: 16, text: "Le dernier rhinocéros blanc."},
    {id: 17, text: "Une chasse au trésor où le trésor est moi."},
    {id: 18, text: "Un dinosaure en peluche."},
    {id: 19, text: "Le côté sombre de la lune."},
    {id: 20, text: "Une romance interdite avec un canard."},
    {id: 21, text: "Raconter des blagues lors d'un enterrement."},
    {id: 22, text: "Un secret de famille gênant."},
    {id: 23, text: "Une attaque de requin."},
    {id: 24, text: "Voler le dentier de grand-père."},
    {id: 25, text: "Une soirée jeux de société qui dégénère."},
    {id: 26, text: "Un distributeur de bonbons illégal."},
    {id: 27, text: "Une nuit sauvage avec Charlie Chaplin."},
    {id: 28, text: "La vérité sur les aliens."},
    {id: 29, text: "Un régime à base de burgers."},
    {id: 30, text: "La fureur de Thor."},
    {id: 31, text: "Une soirée pyjama avec un tigre."},
    {id: 32, text: "La pire piqûre d'insecte de l'histoire."},
    {id: 33, text: "Une mouche trop collante."},
    {id: 34, text: "Un vomi arc-en-ciel."},
    {id: 35, text: "Une date Tinder avec un vampire."},
    {id: 36, text: "Faire un pacte avec le diable."},
    {id: 37, text: "Un mariage arrangé avec un robot."},
    {id: 38, text: "Une grenouille qui rêve d'être une princesse."},
    {id: 39, text: "Un secret honteux révélé en public."},
    {id: 40, text: "Une invasion de punaises de lit."},
    {id: 41, text: "Une licorne qui vomit des arcs-en-ciel."},
    {id: 42, text: "Un canard ninja."},
    {id: 43, text: "Un chat qui contrôle le monde."},
    {id: 44, text: "Une licorne en colère."},
    {id: 45, text: "Un strip-tease de bonhomme de neige."},
    {id: 46, text: "Un koala qui fait du karaoké."},
    {id: 47, text: "Un amour interdit avec un manchot."},
    {id: 48, text: "Un détective qui a perdu son pantalon."},
    {id: 49, text: "Un rendez-vous galant avec un zombie."},
    {id: 50, text: "Un lapin qui sait trop bien danser."},
];


export default reponses